# Copyright (c) 2026, Omar Sabry and contributors
# For license information, please see license.txt

from contact_enhancements.setup.custom_fields import create_contact_enhancements_custom_fields
from contact_enhancements.setup.property_setters import (
	create_contact_dedupe_index_property_setters,
	create_contact_enhancements_index_property_setters,
	create_contact_enhancements_property_setters,
	create_contact_full_name_property_setters,
	create_contact_phone_hidden_field_property_setters,
	create_employee_full_name_property_setters,
	create_supplier_contact_property_setters,
	create_user_contact_property_setters,
)


def after_install():
	create_contact_enhancements_custom_fields()
	create_contact_enhancements_property_setters()
	create_contact_enhancements_index_property_setters()
	create_contact_dedupe_index_property_setters()
	create_contact_full_name_property_setters()
	create_contact_phone_hidden_field_property_setters()
	create_supplier_contact_property_setters()
	create_employee_full_name_property_setters()
	create_user_contact_property_setters()
